In [ ]:
!pip install Numpy

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Logistics_Cleaned_Dataset.csv')
df


Shipment_ID  Order_ID Customer_Name Source_City Destination_City  \
0           10001     12270         Aisha     Kolkata        Hyderabad   
1           10002      5860       Unknown     Kolkata          Unknown   
2           10003     10390       Unknown     Kolkata        Bangalore   
3           10004     10191       Unknown   Hyderabad            Delhi   
4           10005     10734       Unknown     Unknown        Bangalore   
...           ...       ...           ...         ...              ...   
4995        14996      9427       Unknown     Unknown       Coimbatore   
4996        14997     11135          Sita     Kolkata          Unknown   
4997        14998     10573       Unknown   Bangalore          Unknown   
4998        14999      9131          John     Kolkata       Coimbatore   
4999        15000     14900       Unknown     Unknown            Delhi   

     Shipment_Date Delivery_Date Transport_Mode  Weight_Kg  Distance_Km  ...  \
0       29-11-2022    10-12-2022           Road         25          100  ...   
1       02-02-2021    01-02-2022           Road         15          200  ...   
2       01-05-2023    24-12-2022        Unknown         15           50  ...   
3       01-09-2022    20-09-2022            Sea         30          200  ...   
4       29-10-2022    11-02-2022        Unknown          5          400  ...   
...            ...           ...            ...        ...          ...  ...   
4995    06-07-2021    03-01-2021           Road         20          400  ...   
4996    06-04-2023    04-05-2023           Road         20          100  ...   
4997    09-01-2023    31-07-2022           Rail         20           20  ...   
4998    08-07-2022    10-08-2021            Sea          5          400  ...   
4999    04-04-2022    14-11-2022            Sea         20          100  ...   

      Cost  Profit  Selling_Price  Delivery_Status Damage_Flag  \
0      800     400           1200       In Transit           1   
1     1500   -1200            300        Cancelled           1   
2     1500    -300           1200       In Transit           1   
3      800     400           1200        Delivered           1   
4      800     800           1600          Unknown           1   
...    ...     ...            ...              ...         ...   
4995   800     400           1200       In Transit           1   
4996   800    -500            300        Cancelled           1   
4997   800     400           1200       In Transit           1   
4998  1500    -300           1200         Returned           1   
4999  1000    -700            300         Returned           1   

      Delivery_Time_Days  Return_Reason Driver_Rating   Vehicle_Type  \
0                      3     Wrong Item              3      Mini Van   
1                      2           Late              3       Unknown   
2                      8           Late              3          Bike   
3                      1           Late              3          Bike   
4                      6        Unknown              4       Unknown   
...                  ...            ...            ...           ...   
4995                   2        Damaged              1       Unknown   
4996                   1     Wrong Item              5          Bike   
4997                   5        Damaged              4         Truck   
4998                   5        Unknown              2      Mini Van   
4999                   7     Wrong Item              3     Container   

     Fuel_Consumption_Litres  
0                         30  
1                         30  
2                         25  
3                         10  
4                         30  
...                      ...  
4995                      20  
4996                      10  
4997                      15  
4998                      20  
4999                      20  

[5000 rows x 21 columns]

In [ ]:
1.	Use NumPy to calculate mean/median/std for:Weight,Cost,Distance


In [ ]:
import numpy as np
weight = df['Weight_Kg'].to_numpy()
cost = df['Cost'].to_numpy()
distance = df['Distance_Km'].to_numpy()

weight_mean = np.nanmean(weight)
weight_median = np.nanmedian(weight)
weight_std = np.nanstd(weight)

weight_mean, weight_median, weight_std


(np.float64(18.395), np.float64(20.0), np.float64(6.9806142279888235))

In [ ]:
2.Vectorized calculation for profit margin.

In [ ]:
import numpy as np

df['Profit_Margin'] = np.where(
    df['Selling_Price'] > 0,
    ((df['Selling_Price'] - df['Cost']) / df['Selling_Price']) * 100,
    np.nan
)
df


Shipment_ID  Order_ID Customer_Name Source_City Destination_City  \
0           10001     12270         Aisha     Kolkata        Hyderabad   
1           10002      5860       Unknown     Kolkata          Unknown   
2           10003     10390       Unknown     Kolkata        Bangalore   
3           10004     10191       Unknown   Hyderabad            Delhi   
4           10005     10734       Unknown     Unknown        Bangalore   
...           ...       ...           ...         ...              ...   
4995        14996      9427       Unknown     Unknown       Coimbatore   
4996        14997     11135          Sita     Kolkata          Unknown   
4997        14998     10573       Unknown   Bangalore          Unknown   
4998        14999      9131          John     Kolkata       Coimbatore   
4999        15000     14900       Unknown     Unknown            Delhi   

     Shipment_Date Delivery_Date Transport_Mode  Weight_Kg  Distance_Km  ...  \
0       29-11-2022    10-12-2022           Road         25          100  ...   
1       02-02-2021    01-02-2022           Road         15          200  ...   
2       01-05-2023    24-12-2022        Unknown         15           50  ...   
3       01-09-2022    20-09-2022            Sea         30          200  ...   
4       29-10-2022    11-02-2022        Unknown          5          400  ...   
...            ...           ...            ...        ...          ...  ...   
4995    06-07-2021    03-01-2021           Road         20          400  ...   
4996    06-04-2023    04-05-2023           Road         20          100  ...   
4997    09-01-2023    31-07-2022           Rail         20           20  ...   
4998    08-07-2022    10-08-2021            Sea          5          400  ...   
4999    04-04-2022    14-11-2022            Sea         20          100  ...   

     Profit  Selling_Price  Delivery_Status  Damage_Flag Delivery_Time_Days  \
0       400           1200       In Transit            1                  3   
1     -1200            300        Cancelled            1                  2   
2      -300           1200       In Transit            1                  8   
3       400           1200        Delivered            1                  1   
4       800           1600          Unknown            1                  6   
...     ...            ...              ...          ...                ...   
4995    400           1200       In Transit            1                  2   
4996   -500            300        Cancelled            1                  1   
4997    400           1200       In Transit            1                  5   
4998   -300           1200         Returned            1                  5   
4999   -700            300         Returned            1                  7   

      Return_Reason  Driver_Rating  Vehicle_Type  Fuel_Consumption_Litres  \
0        Wrong Item               3     Mini Van                       30   
1              Late               3      Unknown                       30   
2              Late               3         Bike                       25   
3              Late               3         Bike                       10   
4           Unknown               4      Unknown                       30   
...             ...             ...          ...                      ...   
4995        Damaged               1      Unknown                       20   
4996     Wrong Item               5         Bike                       10   
4997        Damaged               4        Truck                       15   
4998        Unknown               2     Mini Van                       20   
4999     Wrong Item               3    Container                       20   

     Profit_Margin  
0        33.333333  
1      -400.000000  
2       -25.000000  
3        33.333333  
4        50.000000  
...            ...  
4995     33.333333  
4996   -166.666667  
4997     33.333333  
4998    -25.000000  
4999   -233.333333  

[5000 rows x 22 columns]

In [ ]:
3.	Identify extreme outliers using NumPy percentile.

In [ ]:
import numpy as np

# Convert Cost column to NumPy array
cost = df['Cost'].to_numpy()

# Calculate Q1, Q3, IQR
Q1 = np.nanpercentile(cost, 25)
Q3 = np.nanpercentile(cost, 75)
IQR = Q3 - Q1

# Define bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = cost[(cost < lower_bound) | (cost > upper_bound)]

lower_bound, upper_bound, outliers[:10]


(np.float64(800.0),
 np.float64(800.0),
 array([1500, 1500, 1500,  500,  200, 1000,  200, 1500, 1500, 1500]))

In [ ]:
4.	Simulate 1000 random delivery delays (Poisson).

In [ ]:
import numpy as np
# Set average delay (lambda)
avg_delay = 3   # 3 days average delay
# Simulate 1000 delivery delays
delivery_delays = np.random.poisson(lam=avg_delay, size=1000)
delivery_delays


array([ 3,  1,  1,  0,  6,  5,  3,  4,  7,  1,  1,  2,  4,  3,  3,  1,  2,
        1,  5,  2,  3,  4,  1,  0,  3,  6,  2,  2,  2,  0,  2,  3,  5,  3,
        2,  2,  2,  2,  5,  5,  3,  4,  0,  1,  2,  3,  3,  3,  4,  2,  2,
        4,  3,  3,  3,  2,  0,  2,  2,  2,  2,  1,  2,  4,  3,  4,  6,  4,
        4,  3,  3,  1,  3,  4,  5,  2,  4,  5,  4,  4,  5,  6,  3,  5,  2,
        1,  6,  5,  2,  1,  4,  3,  3,  3,  5,  4,  5,  3,  3,  3,  4,  6,
        4,  2,  2,  1,  5,  0,  4,  3,  5,  0,  2,  1,  6,  2,  3,  2,  5,
        4,  3,  3,  4,  1,  2,  3,  1,  1,  2,  3,  3,  2,  2,  2,  6,  3,
        5,  3,  3, 11,  1,  1,  6,  4,  3,  1,  1,  3,  6,  2,  1,  4,  2,
        4,  3,  0,  3,  4,  2,  2,  2,  2,  3,  4,  2,  3,  2,  4,  2,  2,
        1,  6,  0,  4,  6,  4,  2,  4,  4,  3,  6,  5,  2,  1,  4,  2,  3,
        4,  3,  5,  2,  2,  3,  1,  2,  1,  2,  1,  4,  4,  0,  1,  0,  4,
        2,  4,  0,  3,  2,  5,  4,  2,  5,  0,  3,  4,  2,  4,  3,  5,  1,
        5,  8,  2,  3,  3

In [ ]:
5.	Probability shipment is damaged (binomial).

In [ ]:

# Number of shipments
n_shipments = 1000

# Probability of damage
p_damage = 0.05   # 5% chance

# Simulate damaged shipments
damaged_shipments = np.random.binomial(
    n=n_shipments,
    p=p_damage,
    size=1
)
damaged_shipments


array([46])